apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcd
  namespace: so1
spec:
  selector:
    matchLabels:
      app: grpcd
  template:
    metadata:
      labels:
        app: grpcd
    spec:
      containers:
      - name: serverg
        image: raulccastillo/serverg:2.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8081
      - name: clientg
        image: raulccastillo/clienteg:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: clientegrpc
  namespace: so1
spec:
  selector:
    app: grpcd
  ports:
  - port: 8080
    targetPort: 8080