apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: so1
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: raulccastillo/consumer:1.0
        env:
          - name: SERVICE_MONGO
            value: mongosvc
          - name: USER
            value: root
          - name: PASS
            value: "1234"
          - name: SERVICE_REDIS
            value: srvredis
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
          
          
          


