apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustapp
  namespace: so1
spec:
  selector:
    matchLabels:
      app: rustapp
  template:
    metadata:
      labels:
        app: rustapp
    spec:
      containers:
      - name: rustclient
        image: raulccastillo/rustclient:3.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
      - name: rustserver
        image: raulccastillo/rustserver:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: clientrust
  namespace: so1
spec:
  type: ClusterIP
  selector:
    app: rustapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000