apiVersion: v1
kind: ConfigMap
metadata:
  name: grafconfig
  namespace: so1
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "redis",
                "orgId": 1,
                "password":"",
                "type": "redis",
                "url": "redis://redis.so1.svc:6379",
                "version": 1
            }
        ]
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: so1
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: config-map
        configMap:
          name: grafconfig
      - name: grafana-storage
        emptyDir: {}
      containers:
      - name: grafana
        image: grafana/grafana:8.4.4
        volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: config-map
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: svcgrana
  namespace: so1
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000