apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmongo
  namespace: so1
spec:
  selector:
    matchLabels:
      app: dbmongo
  template:
    metadata:
      labels:
        app: dbmongo
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: config
      containers:
      - name: dbmongo
        image: mongo
        volumeMounts:
        - name: config-volume
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "1234"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "0.5"
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: so1
spec:
  type: LoadBalancer
  selector:
    app: dbmongo
  ports:
  - port: 27017
    targetPort: 27017