apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: so1
data:
  redis-config: |
    dir /data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisapp
  namespace: so1
spec:
  selector:
    matchLabels:
      run: redisapp 
  template:
    metadata:
      labels:
        run: redisapp
    spec:
      volumes:
      - name: config
        configMap: 
          name: redis-configmap
          items:
          - key: redis-config
            path: redis.conf

      containers:
      - name: redisapp
        image: redis:6.2
        command:
          - redis-server
          - /redisconf/redis.conf
        volumeMounts:
        - mountPath: /redisconf
          name: config
        resources:
          limits:
            cpu: "0.2"
            memory: "128Mi"
        ports:
        - containerPort: 6379 


---
apiVersion: v1
kind: Service
metadata:
  name: srvredis
  namespace: so1
spec:
  selector:
    run: redisapp
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379